//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doktor_Departman
    {
        public int DoktorDoktor_Id { get; set; }
        public int Klinika_DepartmanKlinikaKlinika_Id { get; set; }
        public int Klinika_DepartmanDepartmanDepartman_Id { get; set; }
        public int Doktor_Doktor_Id { get; set; }
        public int Ugovor_Ugovor_Id { get; set; }
    
        public virtual Doktor Doktor { get; set; }
        public virtual Klinika_Departman Klinika_Departman { get; set; }
        public virtual Ugovor Ugovor { get; set; }
    }
}
