//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pregled
    {
        public int Pregled_Id { get; set; }
        public string Opis { get; set; }
        public string Vreme { get; set; }
        public int Doktor_opste_prakse_PregledDoktor_opste_prakseDoktor_Id { get; set; }
    
        public virtual Doktor_opste_prakse_Pregled1 Doktor_opste_prakse_Pregled1 { get; set; }
    }
}
