//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terapija_Specijaliste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terapija_Specijaliste()
        {
            this.Dijagnoza_Specijaliste = new HashSet<Dijagnoza_Specijaliste>();
        }
    
        public int Terapija_Id { get; set; }
        public string Naziv { get; set; }
        public string Opis { get; set; }
        public string Vrsta_Terapije { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dijagnoza_Specijaliste> Dijagnoza_Specijaliste { get; set; }
    }
}
