//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zdravstveni_Karton
    {
        public int Karton_Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string JMBG { get; set; }
        public string Evidencija { get; set; }
        public int Pacijent_Departman_PacijentPacijent_Id { get; set; }
        public int Pacijent_Departman_Klinika_DepartmanKlinikaKlinika_Id { get; set; }
        public int Pacijent_Departman_Klinika_DepartmanDepartmanDepartman_Id { get; set; }
    
        public virtual Pacijent_Departman Pacijent_Departman { get; set; }
    }
}
