
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Departman
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Departman()
    {

        this.Klinika_Departman = new HashSet<Klinika_Departman>();

    }

        public Departman(string naziv, string sprat)
        {
            Naziv = naziv;
            Sprat = sprat;
        }

        public int Departman_Id { get; set; }

    public string Naziv { get; set; }

    public string Sprat { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Klinika_Departman> Klinika_Departman { get; set; }

}

}
