
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Doktor_specijalista_Uput
{

    public int Doktor_specijalistaDoktor_Id { get; set; }

    public Nullable<int> Dijagnoza_SpecijalisteDijagnoza_Id { get; set; }

    public Nullable<int> UputIshod_Id { get; set; }

    public int DoktorDoktor_Id { get; set; }



    public virtual Dijagnoza_Specijaliste Dijagnoza_Specijaliste { get; set; }

    public virtual Doktor Doktor { get; set; }

    public virtual Ishod_Pregleda_Uput Ishod_Pregleda_Uput { get; set; }

}

}
