
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Doktor_opste_prakse_Pregled1
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Doktor_opste_prakse_Pregled1()
    {

        this.Doktor_op_pr_Pregled_Pacijent = new HashSet<Doktor_op_pr_Pregled_Pacijent>();

        this.Pregleds = new HashSet<Pregled>();

    }


    public int Doktor_opste_prakseDoktor_Id { get; set; }

    public int DoktorDoktor_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Doktor_op_pr_Pregled_Pacijent> Doktor_op_pr_Pregled_Pacijent { get; set; }

    public virtual Doktor Doktor { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pregled> Pregleds { get; set; }

}

}
