
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Ishod_Pregleda_Uput
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Ishod_Pregleda_Uput()
    {

        this.Doktor_specijalista_Uput = new HashSet<Doktor_specijalista_Uput>();

    }


    public int Ishod_Id { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Doktor_specijalista_Uput> Doktor_specijalista_Uput { get; set; }

    public virtual Ishod_Pregleda Ishod_Pregleda { get; set; }

}

}
