//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ishod_Pregleda_Dijagnoza
    {
        public Nullable<int> TerapijaTerapija_Id { get; set; }
        public int Ishod_Id { get; set; }
    
        public virtual Ishod_Pregleda Ishod_Pregleda { get; set; }
        public virtual Terapija Terapija { get; set; }
    }
}
