
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Klinika_Departman
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Klinika_Departman()
    {

        this.Doktor_Departman = new HashSet<Doktor_Departman>();

        this.Pacijent_Departman = new HashSet<Pacijent_Departman>();

    }


    public int KlinikaKlinika_Id { get; set; }

    public int DepartmanDepartman_Id { get; set; }



    public virtual Departman Departman { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Doktor_Departman> Doktor_Departman { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pacijent_Departman> Pacijent_Departman { get; set; }

    public virtual Klinika Klinika { get; set; }

}

}
