
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Klinika
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Klinika()
    {

        this.Klinika_Departman = new HashSet<Klinika_Departman>();

    }

        public Klinika(string naziv, string grad, string ulica, string broj, string telefon)
        {
            Naziv = naziv;
            Grad = grad;
            Ulica = ulica;
            Broj = broj;
            Telefon = telefon;
        }

        public int Klinika_Id { get; set; }

    public string Naziv { get; set; }

    public string Grad { get; set; }

    public string Ulica { get; set; }

    public string Broj { get; set; }

    public string Telefon { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Klinika_Departman> Klinika_Departman { get; set; }

}

}
