//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Korisnik
    {
        public Korisnik(string ime, string prezime, string kontakt, string email, string ulica, string broj, string grad, string korisnicko_Ime, string lozinka, string uloga)
        {
            Ime = ime;
            Prezime = prezime;
            Kontakt = kontakt;
            Email = email;
            Ulica = ulica;
            Broj = broj;
            Grad = grad;
            Korisnicko_Ime = korisnicko_Ime;
            Lozinka = lozinka;
            Uloga = uloga;
        }
        public Korisnik()
        {

        }

        public int Korisnik_Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Kontakt { get; set; }
        public string Email { get; set; }
        public string Ulica { get; set; }
        public string Broj { get; set; }
        public string Grad { get; set; }
        public string Korisnicko_Ime { get; set; }
        public string Lozinka { get; set; }
        public string Uloga { get; set; }
    }
}
