//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacijent_Departman
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacijent_Departman()
        {
            this.Zdravstveni_Karton = new HashSet<Zdravstveni_Karton>();
        }
    
        public string Datum_Prijave { get; set; }
        public string Datum_Odjave { get; set; }
        public string Soba { get; set; }
        public int PacijentPacijent_Id { get; set; }
        public int Klinika_DepartmanKlinikaKlinika_Id { get; set; }
        public int Klinika_DepartmanDepartmanDepartman_Id { get; set; }
    
        public virtual Klinika_Departman Klinika_Departman { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zdravstveni_Karton> Zdravstveni_Karton { get; set; }
        public virtual Pacijent Pacijent { get; set; }
    }
}
