
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicApp.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Pacijent
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Pacijent()
    {

        this.Doktor_op_pr_Pregled_Pacijent = new HashSet<Doktor_op_pr_Pregled_Pacijent>();

        this.Pacijent_Departman = new HashSet<Pacijent_Departman>();

    }

        public Pacijent(string ime, string prezime, string kontakt, string adresa)
        {
            Ime = ime;
            Prezime = prezime;
            Kontakt = kontakt;
            Adresa = adresa;
        }

        public int Pacijent_Id { get; set; }

    public string Ime { get; set; }

    public string Prezime { get; set; }

    public string Kontakt { get; set; }

    public string Adresa { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Doktor_op_pr_Pregled_Pacijent> Doktor_op_pr_Pregled_Pacijent { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Pacijent_Departman> Pacijent_Departman { get; set; }

}

}
